[package]
name = "veil-server"
version = "0.0.0"
edition = "2021"

[dependencies]
prost = "0.13.4"
webrtc = "0.12.0"
compositor = { path = "../../packages/compositor" }
encoder = { path = "../../packages/encoder" }
