[package]
name = "veil_proto"
version = "0.0.0"
edition = "2021"

[lib]
name = "veil_proto"
path = "lib.rs"

[dependencies]
bytes = "1.1.0"
prost = "0.13.1"
pbjson = "0.7"
pbjson-types = "0.7"
serde = "1.0"
tonic = { version = "0.12", features = ["gzip"] }