// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package generated

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WebRTCSignallingClient is the client API for WebRTCSignalling service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WebRTCSignallingClient interface {
	GetOffer(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*SDP, error)
	SendAnswer(ctx context.Context, in *SDP, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetCandidate(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (WebRTCSignalling_GetCandidateClient, error)
	SendCandidate(ctx context.Context, in *ICECandidate, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type webRTCSignallingClient struct {
	cc grpc.ClientConnInterface
}

func NewWebRTCSignallingClient(cc grpc.ClientConnInterface) WebRTCSignallingClient {
	return &webRTCSignallingClient{cc}
}

func (c *webRTCSignallingClient) GetOffer(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*SDP, error) {
	out := new(SDP)
	err := c.cc.Invoke(ctx, "/webrtc_signalling.WebRTCSignalling/GetOffer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webRTCSignallingClient) SendAnswer(ctx context.Context, in *SDP, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/webrtc_signalling.WebRTCSignalling/SendAnswer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webRTCSignallingClient) GetCandidate(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (WebRTCSignalling_GetCandidateClient, error) {
	stream, err := c.cc.NewStream(ctx, &WebRTCSignalling_ServiceDesc.Streams[0], "/webrtc_signalling.WebRTCSignalling/GetCandidate", opts...)
	if err != nil {
		return nil, err
	}
	x := &webRTCSignallingGetCandidateClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type WebRTCSignalling_GetCandidateClient interface {
	Recv() (*ICECandidate, error)
	grpc.ClientStream
}

type webRTCSignallingGetCandidateClient struct {
	grpc.ClientStream
}

func (x *webRTCSignallingGetCandidateClient) Recv() (*ICECandidate, error) {
	m := new(ICECandidate)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *webRTCSignallingClient) SendCandidate(ctx context.Context, in *ICECandidate, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/webrtc_signalling.WebRTCSignalling/SendCandidate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WebRTCSignallingServer is the server API for WebRTCSignalling service.
// All implementations must embed UnimplementedWebRTCSignallingServer
// for forward compatibility
type WebRTCSignallingServer interface {
	GetOffer(context.Context, *emptypb.Empty) (*SDP, error)
	SendAnswer(context.Context, *SDP) (*emptypb.Empty, error)
	GetCandidate(*emptypb.Empty, WebRTCSignalling_GetCandidateServer) error
	SendCandidate(context.Context, *ICECandidate) (*emptypb.Empty, error)
	mustEmbedUnimplementedWebRTCSignallingServer()
}

// UnimplementedWebRTCSignallingServer must be embedded to have forward compatible implementations.
type UnimplementedWebRTCSignallingServer struct {
}

func (UnimplementedWebRTCSignallingServer) GetOffer(context.Context, *emptypb.Empty) (*SDP, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOffer not implemented")
}
func (UnimplementedWebRTCSignallingServer) SendAnswer(context.Context, *SDP) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendAnswer not implemented")
}
func (UnimplementedWebRTCSignallingServer) GetCandidate(*emptypb.Empty, WebRTCSignalling_GetCandidateServer) error {
	return status.Errorf(codes.Unimplemented, "method GetCandidate not implemented")
}
func (UnimplementedWebRTCSignallingServer) SendCandidate(context.Context, *ICECandidate) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendCandidate not implemented")
}
func (UnimplementedWebRTCSignallingServer) mustEmbedUnimplementedWebRTCSignallingServer() {}

// UnsafeWebRTCSignallingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WebRTCSignallingServer will
// result in compilation errors.
type UnsafeWebRTCSignallingServer interface {
	mustEmbedUnimplementedWebRTCSignallingServer()
}

func RegisterWebRTCSignallingServer(s grpc.ServiceRegistrar, srv WebRTCSignallingServer) {
	s.RegisterService(&WebRTCSignalling_ServiceDesc, srv)
}

func _WebRTCSignalling_GetOffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebRTCSignallingServer).GetOffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/webrtc_signalling.WebRTCSignalling/GetOffer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebRTCSignallingServer).GetOffer(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebRTCSignalling_SendAnswer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SDP)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebRTCSignallingServer).SendAnswer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/webrtc_signalling.WebRTCSignalling/SendAnswer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebRTCSignallingServer).SendAnswer(ctx, req.(*SDP))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebRTCSignalling_GetCandidate_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WebRTCSignallingServer).GetCandidate(m, &webRTCSignallingGetCandidateServer{stream})
}

type WebRTCSignalling_GetCandidateServer interface {
	Send(*ICECandidate) error
	grpc.ServerStream
}

type webRTCSignallingGetCandidateServer struct {
	grpc.ServerStream
}

func (x *webRTCSignallingGetCandidateServer) Send(m *ICECandidate) error {
	return x.ServerStream.SendMsg(m)
}

func _WebRTCSignalling_SendCandidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ICECandidate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebRTCSignallingServer).SendCandidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/webrtc_signalling.WebRTCSignalling/SendCandidate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebRTCSignallingServer).SendCandidate(ctx, req.(*ICECandidate))
	}
	return interceptor(ctx, in, info, handler)
}

// WebRTCSignalling_ServiceDesc is the grpc.ServiceDesc for WebRTCSignalling service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WebRTCSignalling_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "webrtc_signalling.WebRTCSignalling",
	HandlerType: (*WebRTCSignallingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOffer",
			Handler:    _WebRTCSignalling_GetOffer_Handler,
		},
		{
			MethodName: "SendAnswer",
			Handler:    _WebRTCSignalling_SendAnswer_Handler,
		},
		{
			MethodName: "SendCandidate",
			Handler:    _WebRTCSignalling_SendCandidate_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetCandidate",
			Handler:       _WebRTCSignalling_GetCandidate_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "webrtc_signalling.proto",
}
